### PR TITLE
Add headless peer services for StatefulSet 

### PR DESCRIPTION
**Pull request by howardlau1999**
After merging this PR, the operator can create a minimum working cluster! I have manually tested it on my cluster.

### CODE REVIEW

**Comment by chrislusf** [comment]
Great Job!!!!!!

Could you please write some readme on how this works? I vaguely know why the peer services are needed, but not too sure still.

**Comment by howardlau1999** [comment]
> Great Job!!!!!!
> 
> Could you please write some readme on how this works? I vaguely know why the peer services are needed, but not too sure still.

Peer services are required by StatefulSet which is used to generate stable DNS names for pods created. Then we can use <name>-<ordinal>.<peer-svc> to access a specific pod. A normal service will randomly forward traffic to any pods, which may cause problems. So we just follow the practices suggested by the official kubernetes documents.

**Comment by chrislusf** [comment]
Thanks!

One related thing: the filer also supports `-peers` option. Filers need this to synchronize metadata updates, especially for leveldb filer store. It is also needed when using mount.

https://github.com/chrislusf/seaweedfs/blob/master/weed/command/filer.go#L66

**Comment by howardlau1999** [comment]
> Thanks!
> 
> One related thing: the filer also supports `-peers` option. Filers need this to synchronize metadata updates, especially for leveldb filer store. It is also needed when using mount.
> 
> https://github.com/chrislusf/seaweedfs/blob/master/weed/command/filer.go#L66

Thanks. I didn't know that. I thought that if filers are connected to a shared store then they are stateless. Will update in another PR.

**Pull request merged**
